if(CMAKE_C_COMPILER_ID STREQUAL "OpenWatcom")
  # CMake support for Watcom assembler
  set(CMAKE_ASM_USE_WATCOM_QUOTE 1)

  foreach(type CREATE_SHARED_LIBRARY CREATE_SHARED_MODULE LINK_EXECUTABLE)
    set(CMAKE_ASM_${type}_USE_WATCOM_QUOTE 1)
  endforeach()

  set(CMAKE_ASM_COMPILE_OBJECT
    "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> -fo<OBJECT> -c <SOURCE>")

  # warning level
  string(APPEND CMAKE_ASM_FLAGS_INIT " -w3")
  # debug options
  string(APPEND CMAKE_ASM_FLAGS_DEBUG_INIT " -d2")
  string(APPEND CMAKE_ASM_FLAGS_MINSIZEREL_INIT " -s -os -d0 -dNDEBUG")
  string(APPEND CMAKE_ASM_FLAGS_RELEASE_INIT " -s -ot -d0 -dNDEBUG")
  string(APPEND CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT " -s -ot -d1 -dNDEBUG")
endif()
